import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class login extends javax.swing.JFrame {
    // deklarasi
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public login() {
        initComponents();
        //pemanggilan fungsi koneksi database yang sudah kita buat pada class koneksi.java
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        bt_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_name(evt);
            }
        });

        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pass(evt);
            }
        });

        bt_login.setText("Login");
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txt_pass)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(bt_login)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel1.setText("Login Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_pass(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pass
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pass

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
                                         
                
        try {
            sql = "SELECT * FROM admin WHERE username='"+txt_name.getText()+"' AND password='"+txt_pass.getText()+"'";
            rs = stat.executeQuery(sql);
            if(rs.next()){
                if(txt_name.getText().equals(rs.getString("username")) && txt_pass.getText().equals(rs.getString("password"))){
                    String side1 = (JOptionPane.showInputDialog("Siapa nama kamu?"));
                    String side2 = (JOptionPane.showInputDialog("kamu sering merasa cepat lemas? ( y / t )"));
                    String side3 = (JOptionPane.showInputDialog("kamu sering merasa cepat lelah? ( y / t )"));
                    String side4 = (JOptionPane.showInputDialog("kamu sering merasa sakit kepala? ( y / t )"));
                    String side5 = (JOptionPane.showInputDialog("kamu sering merasa cepat pusing? ( y / t )"));
                    String side6 = (JOptionPane.showInputDialog("kamu sering merasa cepat ngantuk? ( y / t )"));
                    String side7 = (JOptionPane.showInputDialog("apa kulit kamu terlihat kekuningan? ( y / t )"));
                    String side8 = (JOptionPane.showInputDialog("apa nafas kamu pendek? ( y / t )"));

                    if ( side2.contains("y") && side3.contains("y") && side4.contains("y") && side5.contains("y") && side6.contains("y") && side7.contains("y") && side7.contains("y")){
                        String nama = side1;
                        JOptionPane.showMessageDialog(null,"hai, kamu beresiko besar terkena anemia. segera konsultasikan ke dokter ya,  "+nama);
                    } else if ( side2.contains("y") && side3.contains("t") && side4.contains("y") && side5.contains("y") && side6.contains("y") && side7.contains("y") && side8.contains("y")){
                        String nama = side1;
                        JOptionPane.showMessageDialog(null, "hai, kamu beresiko besar terkena anemia. segera konsultasikan ke dokter ya,"+nama);
                    } else if ( side2.contains("y") && side3.contains("t") && side4.contains("y") && side5.contains("y") && side6.contains("t") && side7.contains("y") && side8.contains("y")){
                        String nama = side1;
                        JOptionPane.showMessageDialog(null, "hai, kamu beresiko besar terkena anemia. segera konsultasikan ke dokter ya,"+nama);
                    } else if ( side2.contains("y") && side3.contains("t") && side4.contains("y") && side5.contains("y") && side6.contains("t") && side7.contains("y") && side8.contains("t")){
                        String nama = side1;
                        JOptionPane.showMessageDialog(null, "hai, kamu beresiko besar terkena anemia. segera konsultasikan ke dokter ya,"+nama);
                    } else if ( side2.contains("y") && side3.contains("t") && side4.contains("y") && side5.contains("y") && side6.contains("y") && side7.contains("t") && side8.contains("t")){
                        String nama = side1;
                        JOptionPane.showMessageDialog(null, "hai, kamu beresiko kecil terkena anemia. kalau gejalanya memburuk segera konsultasikan ke dokter ya,"+nama);
                    } else if ( side2.contains("y") && side3.contains("y") && side4.contains("y") && side5.contains("t") && side6.contains("y") && side7.contains("t") && side8.contains("t")){
                        String nama = side1;
                        JOptionPane.showMessageDialog(null, "kamu beresiko anemia,"+nama);
                    } else if ( side2.contains("t") && side3.contains("y") && side4.contains("y") && side5.contains("y") && side6.contains("y") && side7.contains("t") && side8.contains("t")){
                        String nama = side1;
                        JOptionPane.showMessageDialog(null, "kamu beresiko anemia,"+nama);
                    } else if ( side2.contains("y") && side3.contains("y") && side4.contains("y") && side5.contains("y") && side6.contains("t") && side7.contains("t") && side8.contains("t")){
                        String nama = side1;
                        JOptionPane.showMessageDialog(null, "hai, kamu beresiko kecil terkena anemia. kalau gejalanya memburuk segera konsultasikan ke dokter ya,"+nama);
                    } else if ( side2.contains("t") && side3.contains("t") && side4.contains("y") && side5.contains("y") && side6.contains("y") && side7.contains("t") && side8.contains("t")){
                        String nama = side1;
                        JOptionPane.showMessageDialog(null, "hai, kamu beresiko kecil terkena anemia. kalau gejalanya memburuk segera konsultasikan ke dokter ya,"+nama);
                    } else if ( side2.contains("t") && side3.contains("y") && side4.contains("y") && side5.contains("t") && side6.contains("y") && side7.contains("t") && side8.contains("t")){
                        String nama = side1;
                        JOptionPane.showMessageDialog(null, "kamu beresiko anemia, "+nama);
                    } else if ( side2.contains("y") && side3.contains("t") && side4.contains("y") && side5.contains("t") && side6.contains("y") && side7.contains("t") && side8.contains("t")){
                        String nama = side1;
                        JOptionPane.showMessageDialog(null, "kamu beresiko anemia, "+nama);
                    } else if ( side2.contains("y") && side3.contains("y") && side4.contains("t") && side5.contains("t") && side6.contains("y") && side7.contains("t") && side8.contains("t")){
                        String nama = side1;
                        JOptionPane.showMessageDialog(null, "kamu beresiko anemia, "+nama);
                    } else{
                        String nama = side1;
                        JOptionPane.showMessageDialog(null, "kamu beresiko anemia, "+nama);
                    }
                }
            }else{
                    JOptionPane.showMessageDialog(null, "username atau password salah");
                }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }      // TODO add your handling code here:
    }//GEN-LAST:event_bt_loginActionPerformed

    private void txt_name(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_name
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_name

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pass;
    // End of variables declaration//GEN-END:variables
}
