/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
import java.awt.Component;
import javax.swing.JOptionPane;
public class nono extends javax.swing.JFrame {
   

    /**
     * Creates new form nono
     */
    public nono() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        String side1 = (JOptionPane.showInputDialog("Siapa nama kamu?"));
        String side2 = (JOptionPane.showInputDialog("kamu sering merasa cepat lemas? ( y / t )"));
        String side3 = (JOptionPane.showInputDialog("kamu sering merasa cepat lelah? ( y / t )"));
        String side4 = (JOptionPane.showInputDialog("kamu sering merasa sakit kepala? ( y / t )"));
        String side5 = (JOptionPane.showInputDialog("kamu sering merasa cepat pusing? ( y / t )"));
        String side6 = (JOptionPane.showInputDialog("kamu sering merasa cepat ngantuk? ( y / t )"));
        String side7 = (JOptionPane.showInputDialog("apa kulit kamu terlihat kekuningan? ( y / t )"));
        String side8 = (JOptionPane.showInputDialog("apa nafas kamu pendek? ( y / t )"));
                
        if ( side2.contains("y") && side3.contains("y") && side4.contains("y") && side5.contains("y") && side6.contains("y") && side7.contains("y") && side7.contains("y")){
            String nama = side1;
            JOptionPane.showMessageDialog(null,"hai, kamu beresiko besar terkena anemia. segera konsultasikan ke dokter ya,  "+nama);
        } else if ( side2.contains("y") && side3.contains("t") && side4.contains("y") && side5.contains("y") && side6.contains("y") && side7.contains("y") && side8.contains("y")){
            String nama = side1;
            JOptionPane.showMessageDialog(null, "hai, kamu beresiko besar terkena anemia. segera konsultasikan ke dokter ya,"+nama);
        } else if ( side2.contains("y") && side3.contains("t") && side4.contains("y") && side5.contains("y") && side6.contains("t") && side7.contains("y") && side8.contains("y")){
            String nama = side1;
            JOptionPane.showMessageDialog(null, "hai, kamu beresiko besar terkena anemia. segera konsultasikan ke dokter ya,"+nama);
        } else if ( side2.contains("y") && side3.contains("t") && side4.contains("y") && side5.contains("y") && side6.contains("t") && side7.contains("y") && side8.contains("t")){
            String nama = side1;
            JOptionPane.showMessageDialog(null, "hai, kamu beresiko besar terkena anemia. segera konsultasikan ke dokter ya,"+nama);
        } else if ( side2.contains("y") && side3.contains("t") && side4.contains("y") && side5.contains("y") && side6.contains("y") && side7.contains("t") && side8.contains("t")){
            String nama = side1;
            JOptionPane.showMessageDialog(null, "hai, kamu beresiko kecil terkena anemia. kalau gejalanya memburuk segera konsultasikan ke dokter ya,"+nama);
        } else if ( side2.contains("y") && side3.contains("y") && side4.contains("y") && side5.contains("t") && side6.contains("y") && side7.contains("t") && side8.contains("t")){
            String nama = side1;
            JOptionPane.showMessageDialog(null, "kamu beresiko anemia,"+nama);
        } else if ( side2.contains("t") && side3.contains("y") && side4.contains("y") && side5.contains("y") && side6.contains("y") && side7.contains("t") && side8.contains("t")){
            String nama = side1;
            JOptionPane.showMessageDialog(null, "kamu beresiko anemia,"+nama);
        } else if ( side2.contains("y") && side3.contains("y") && side4.contains("y") && side5.contains("y") && side6.contains("t") && side7.contains("t") && side8.contains("t")){
            String nama = side1;
            JOptionPane.showMessageDialog(null, "hai, kamu beresiko kecil terkena anemia. kalau gejalanya memburuk segera konsultasikan ke dokter ya,"+nama);
        } else if ( side2.contains("t") && side3.contains("t") && side4.contains("y") && side5.contains("y") && side6.contains("y") && side7.contains("t") && side8.contains("t")){
            String nama = side1;
            JOptionPane.showMessageDialog(null, "hai, kamu beresiko kecil terkena anemia. kalau gejalanya memburuk segera konsultasikan ke dokter ya,"+nama);
        } else if ( side2.contains("t") && side3.contains("y") && side4.contains("y") && side5.contains("t") && side6.contains("y") && side7.contains("t") && side8.contains("t")){
            String nama = side1;
            JOptionPane.showMessageDialog(null, "kamu beresiko anemia, "+nama);
        } else if ( side2.contains("y") && side3.contains("t") && side4.contains("y") && side5.contains("t") && side6.contains("y") && side7.contains("t") && side8.contains("t")){
            String nama = side1;
            JOptionPane.showMessageDialog(null, "kamu beresiko anemia, "+nama);
        } else if ( side2.contains("y") && side3.contains("y") && side4.contains("t") && side5.contains("t") && side6.contains("y") && side7.contains("t") && side8.contains("t")){
            String nama = side1;
            JOptionPane.showMessageDialog(null, "kamu beresiko anemia, "+nama);
        } else{
            String nama = side1;
            JOptionPane.showMessageDialog(null, "kamu beresiko anemia, "+nama);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new nono().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
